model_list:
  - model_name: "*" # Memungkinkan semua model di Ollama diakses lewat LiteLLM
    litellm_params:
      model: ollama_chat/* # Menghubungkan ke endpoint chat Ollama
      api_base: "http://${OLLAMA_CONTAINER_NAME:-ollama-server}:${OLLAMA_PORT:-11434}" # Menggunakan hostname service di docker-compose

general_settings:
  master_key: "${LITELLM_MASTER_KEY}" # API Key utama yang akan dicek
  database_url: "postgresql://${LITELLM_DB_USERNAME}:${LITELLM_DB_PASSWORD}@${LITELLM_DB_CONTAINER_NAME}:5432/${LITELLM_DB_NAME}" # Database untuk menyimpan data
